pipeline{
    agent any
    environment {
        AWS_ACCESS_KEY_ID= credentials('aws_access_key_id')
        AWS_SECRET_KEY = credentials('aws_secret_key')
        PATH = "/opt/homebrew/bin:$PATH"
    }
    stages{
        stage('Clone Repo'){
            steps {
                git(
                    branch: 'main', 
                    url: 'https://github.com/KshitizStha901/Terraform-Kshitiz.git'
                )
            }
        }
        stage('Terraform init')
        {
            steps{
            dir ('TF-S3'){
                script{
                    sh 'terraform init'
                    echo 'Initializing Terraform..........'
                }
            }
            }
        }
        stage('Terraform Plan')
        {
            steps{
            dir('TF-S3'){
                script{
                    sh 'terraform plan'
                    echo 'Planning Terraform............'
                }
            }
            }
        }
        stage (' Terraform Apply')
        {
            steps{
            dir('TF-S3'){
                script{
                    sh 'terraform apply -auto-approve'
                     echo 'Applying changes............'
                }
            }
            }
        }
    }
}